version: '3.7'
services:
  node_app:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'

  postgres_service:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app